### ISSUE TITLE
Need a good explanation paragraph of what this does.

### ISSUE THREAD

**Issue by code-reaper08** [code-reaper08/dev#1]
## Write a good, conveying paragraph of what this project does.

<br>

__note__ :
Use "**dev**" in the place of the name of the project, in the context.

**Comment by lemonnuggets** [comment]
I see that there are a few other issues that you are looking for help on. I'd love to see if this is a project I can help out with but without knowing why it exists in the first place, there isn't much I can do. So are you looking for help on this documentation part as well or is that something you'll have to do yourself?

**Comment by code-reaper08** [comment]
### Hello @lemonnuggets 😄 , It's so kind of you to involve in the project.

It's basically a **Linkedln background image generator**, which uses **GitHub API** for fetching stats and present them in a downloadable form of a card ( Something like that ).

It takes the **GitHub username** as input and presents the respective account's stats in presentable card-like stuff, which can be downloaded and used as a background image for Linkedln.

So, I present you the steps for the process,

1.  Give your GitHub username as input:

![step1](https://user-images.githubusercontent.com/64256342/116588000-a5366400-a938-11eb-8678-68704b61494e.png)

2. It presents you the card, which is interactable ( Play with it a bit ) :

![step2](https://user-images.githubusercontent.com/64256342/116588145-d020b800-a938-11eb-93dd-46181f331660.png)

3. Download the card as it is or change the theme by pressing the `theme` button.

![step3](https://user-images.githubusercontent.com/64256342/116588270-f6465800-a938-11eb-81e2-8d93c10af945.png)


## So at last, what I want in this issue is  **"I need a paragraph conveying all this process in an engaging tone, to replace the `lorem Ipsum paragraph in **step1**"**


### Any help is welcomed and appreciated.
### Feel free to ask doubts regarding the issue.

**Comment by lemonnuggets** [comment]
Oooh okay, I understand now.  But maybe a paragraph explanation would be overkill. Wouldn't it be enough to have something like this?

![image](https://user-images.githubusercontent.com/63046776/116645879-62a27500-a994-11eb-96a9-73a3e980b353.png)

**Comment by code-reaper08** [comment]
> Oooh okay, I understand now. But maybe a paragraph explanation would be overkill. Wouldn't it be enough to have something like this?
> 
> ![image](https://user-images.githubusercontent.com/63046776/116645879-62a27500-a994-11eb-96a9-73a3e980b353.png)

## Hey @lemonnuggets 😃 
This looks **good, concise, and on point.**, Awesome work tbh. 😉 
It would be great if you make a fork and PR soon with the changes, I would be happy to merge.
